name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Shlok-2006
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23B11226&color_dots=%23080808,%23240000,%23550000,%23800010,%23B11226
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%23B11226&color_dots=%23080808,%23240000,%23550000,%23800010,%23B11226

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
